from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from assay_calib.backtest import FeePolicy, _arbitrage_leg, _profitable_fraction, run_policy

_FIXTURE = Path(__file__).resolve().parents[2] / "test" / "fixtures" / "fee_blend.json"


class TestMatchesSolidity:
    """
    The backtest reimplements `FeeBlend` in Python to evaluate policies over historical flow.
    Its conclusions are only meaningful if that reimplementation matches the deployed
    formula, and nothing about having two languages enforces it. Both sides assert against
    this fixture, which was generated by the Solidity implementation itself.
    """

    def _cases(self) -> list[dict]:
        return json.loads(_FIXTURE.read_text())

    def test_fixture_is_present_and_populated(self) -> None:
        assert len(self._cases()) > 0, "fixture missing; regenerate it from the Solidity library"

    def test_quote_matches_every_fixture_case(self) -> None:
        for case in self._cases():
            policy = FeePolicy(
                name="fixture",
                base_fee_pips=500.0,
                min_fee_pips=100.0,
                max_fee_pips=10_000.0,
                capture_share_bps=float(case["share"]),
            )
            # The fixture stores drift in ticks; the policy takes a signed price fraction.
            mispricing = np.array([case["drift"] / 10_000.0])
            assert policy.quote_pips(mispricing)[0] == pytest.approx(case["quote"], abs=1e-6), (
                f"python quote diverged from solidity at {case}"
            )


class TestArbitrageResponse:
    """
    The counterfactual only means anything if the arbitrageur reacts. These pin the reaction.
    """

    def test_higher_fee_never_increases_traded_size(self) -> None:
        mispricing = np.array([0.005, 0.005, 0.005])
        notional = np.array([1_000.0, 1_000.0, 1_000.0])

        cheap, _ = _arbitrage_leg(mispricing, notional, np.array([500.0] * 3), 500.0)
        dear, _ = _arbitrage_leg(mispricing, notional, np.array([2_000.0] * 3), 500.0)
        assert dear.sum() < cheap.sum()

    def test_static_policy_reproduces_the_observed_volume(self) -> None:
        """
        The historical notional already reflects arbitrage against the pool's static fee, so
        replaying that fee must return exactly what was observed. If it did not, every
        comparison would be measured against a baseline that never happened.
        """
        mispricing = np.array([0.002, 0.01, -0.004])
        notional = np.array([5_000.0, 20_000.0, 1_000.0])

        traded, _ = _arbitrage_leg(mispricing, notional, np.array([500.0] * 3), 500.0)
        assert traded == pytest.approx(notional)

    def test_fee_above_the_drift_stops_the_trade(self) -> None:
        traded, _ = _arbitrage_leg(
            np.array([0.0001]), np.array([1_000.0]), np.array([5_000.0]), 500.0
        )
        assert traded[0] == 0.0

    def test_residual_drift_grows_with_the_fee(self) -> None:
        mispricing = np.array([0.01])
        notional = np.array([1_000.0])

        _, cheap = _arbitrage_leg(mispricing, notional, np.array([500.0]), 500.0)
        _, dear = _arbitrage_leg(mispricing, notional, np.array([4_000.0]), 500.0)
        assert dear[0] > cheap[0], "a higher fee must leave the pool further from its reference"

    def test_profitable_fraction_is_bounded(self) -> None:
        drift = np.array([0.0, 1.0, 100.0, 10_000.0])
        fee = np.array([500.0, 500.0, 500.0, 500.0])
        fraction = _profitable_fraction(drift, fee)
        assert np.all(fraction >= 0.0) and np.all(fraction <= 1.0)


class TestPolicyAccounting:
    def _frame(self) -> pd.DataFrame:
        return pd.DataFrame(
            {
                "signed_mispricing": [0.01, -0.01, 0.0005, -0.0005],
                "notional_usd": [50_000.0, 50_000.0, 10_000.0, 10_000.0],
                "informed": [1.0, 0.0, 0.0, 0.0],
            }
        )

    def test_static_policy_quotes_one_fee_to_everyone(self) -> None:
        policy = FeePolicy("static", 500.0, 500.0, 500.0, 0.0)
        quotes = policy.quote_pips(self._frame()["signed_mispricing"].to_numpy())
        assert len(set(quotes)) == 1, "a zero capture share must not respond to drift"

    def test_capture_share_quotes_directions_differently(self) -> None:
        policy = FeePolicy("assay", 500.0, 100.0, 10_000.0, 5_000.0)
        quotes = policy.quote_pips(np.array([0.01, -0.01]))
        assert quotes[0] > quotes[1], "capturing drift must cost more than adding to it"

    def test_charging_more_reduces_what_arbitrage_extracts(self) -> None:
        df = self._frame()
        static = run_policy(
            df, FeePolicy("static", 500.0, 500.0, 500.0, 0.0), "informed", 0.05, 500.0
        )
        assay = run_policy(
            df, FeePolicy("assay", 500.0, 100.0, 10_000.0, 5_000.0), "informed", 0.05, 500.0
        )
        assert assay.lp_adverse_selection_usd < static.lp_adverse_selection_usd

    def test_elasticity_of_zero_retains_all_uninformed_volume(self) -> None:
        df = self._frame()
        result = run_policy(
            df, FeePolicy("assay", 500.0, 100.0, 10_000.0, 5_000.0), "informed", 0.0, 500.0
        )
        assert result.uninformed_volume_usd == pytest.approx(70_000.0)

    def test_higher_elasticity_drives_more_uninformed_volume_away(self) -> None:
        df = self._frame()
        policy = FeePolicy("assay", 500.0, 100.0, 10_000.0, 5_000.0)
        patient = run_policy(df, policy, "informed", 0.01, 500.0)
        skittish = run_policy(df, policy, "informed", 0.30, 500.0)
        assert skittish.uninformed_volume_usd < patient.uninformed_volume_usd
